name: Generate Animation

on:
  # Executa automaticamente todos os dias à meia-noite
  schedule:
    - cron: "0 0 * * *"
  # Permite executar manualmente o trabalho a qualquer momento
  workflow_dispatch:
  # Executa a cada push na branch master
  push:
    branches:
      - master
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate GitHub Contribution Grid Snake SVG
        uses: Hacker-Bug-Hunter/Hacker-Bug-Hunter/resources/main/main@latest
        with:
          github_user_name: Hacker-Bug-Hunter
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push GitHub Contribution Grid Snake SVG to the Output Branch
        uses: Hacker-Bug-Hunter/Hacker-Bug-Hunter/resources/dev/main@latest
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
