name: Create and Delete File

on:
  schedule:
    - cron: "1 0 * * *"
  workflow_dispatch:

jobs:
  createAndDeleteFile:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Adicione essa linha se precisar de submódulos


    - name: Go to the Hacker-Bug-Hunter/
      run: cd ../..
      
    - name: Create Empty File
      run: touch .py

    - name: List Files
      run: ls

    - name: Wait for 30 seconds
      run: sleep 1

    - name: Delete File
      run: rm .py

    - name: List Files After Deletion
      run: ls
