name: Generate SVGs

on:
 schedule:
    - cron: "2 0 * * *"
 workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub Contribution Grid Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: visnowden
          outputs: |
            snake/github-contribution-grid-snake.svg
            snake/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Move SVG files to custom directory and Commit and push changes
        run: |
          git checkout -b output
          git config user.name "visnowden"
          git config user.email "72585285+visnowden@users.noreply.github.com"
          git add snake/
          git push -u origin output
        env:
          AUTH_TOKEN: ${{ secrets.snake }}
