name: Generate Animation

on:
  schedule:
    - cron: "2 0 * * *"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate GitHub Contribution Grid Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: visnowden
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: ls
        run: ls -a
      - name: pwd
        run: pwd
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: my_directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
