name: compare and update

on:
  push:
    branches: ["raw"]
  schedule:
    - cron: "3 0 * * *"
  workflow_dispatch:

jobs:
  compare_and_update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: raw
        clean: false

    # - name: Move the files
    #   run: |
    #     mkdir raw_branch_files/
    #     mv ./.github/workflows/compare_update.py ./raw_branch_files/

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main

    - name: Move the files
      run: |
        ls -la
    # ls -la ./raw_branch_files/
    #     mv ./raw_branch_files/* ./s

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
        architecture: x64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      run: python .github/workflows/streak/compare_update.py
