name: compare and update

on:
  schedule:
    - cron: "3 0 * * *"
  workflow_dispatch:

jobs:
  compare_and_update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64

    - name: Install dependencies
      run: |
        echo ===================
        ls -la
        echo ===================
        cwd
        echo ===================
        python -m pip install --upgrade pip
        pip install -r .github/workflows/streak/requirements.txt

    - name: Run Python script
      run: python .github/workflows/streak/compare_update.py
