name: compare and update

on:
  push:
    branches: ["raw"]
  schedule:
    - cron: "3 0 * * *"
  workflow_dispatch:

jobs:
  compare_and_update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ghange to branch raw
      run: git checkout raw
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: raw

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/streak/requirements.txt

    - name: Run Python script
      run: python .github/workflows/streak/compare_update.py
