name: compare and update

on:
  push:
    branches: ["raw"]
  schedule:
    - cron: "3 0 * * *"
  workflow_dispatch:
    inputs:
      branch:
        description: "Select the branch to run the workflow"
        default: "raw"
        required: true

jobs:
  compare_and_update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # Faz o download completo do repositório
        ref: raw         # Garante o checkout da branch "raw"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requests

    - name: Run Python script
      run: python .github/workflows/streak/compare_update.py
