name: 👀

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  compare_and_update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/streak/👀.txt

    - name: Run Python script
      run: python .github/workflows/👀.py
